name: Check Docs

on:
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check Docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Check docs type correctness
      run: |
        make docs-check

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Render Docs
      uses: quarto-dev/quarto-actions/render@v2
      with:
        path: docs/
