name: Publish to PyPI

on:
  push:
    branches: [main]

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Check type correctness
      run: |
        make checkall

    - name: Run tests
      run: |
        make testall

    - name: Build
      run: hatch build

    - name: Publish
      env:
        HATCH_INDEX_USER: ${{ secrets.HATCH_INDEX_USER }}
        HATCH_INDEX_AUTH: ${{ secrets.HATCH_INDEX_AUTH }}
      run: hatch publish
